
service: test

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

functions:
  hello:
    handler: handler.hello

resources:
  Resources:

    # Create the IAM Role for the Step Function
    TestStepFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        # Refer to:
        # https://docs.aws.amazon.com/step-functions/latest/dg/procedure-create-iam-role.html
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - states.us-east-1.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          -
            PolicyName: allow-lambda
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: "*"

    # Define the Step Function
    TestStepFunction:
      Type: AWS::StepFunctions::StateMachine
      Properties:
        RoleArn:
          Fn::GetAtt: [ TestStepFunctionRole, Arn ]

        # This could use Fn:Join to do better string concatination and
        # not hard code the lambda name and make usre of Ref: [ AWS:AccountId]
        # instead of storing the accountId in the config.
        DefinitionString: |
          {
            "Comment": "Test workflow",
            "StartAt": "hello",
            "States": {
              "hello": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:us-east-1:${file(config.yml):accountId}:function:test-dev-hello",
                "End": true
              }
            }
          }

